name: Create .env file
on: [push]

jobs:
  create-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "API=${{ secrets.API }}" >> .env
