name: Inject Secrets into script.js

on:
  push:
    branches:
      - main

jobs:
  inject-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Inject Secrets into script.js
        run: |
          # API 키를 apiKey.js에 주입
          echo "const apiKey = '${{ secrets.MAPLE_API_KEY }}';" > ./apiKey.js
          
          # script.js에 apiKey.js를 import하는 코드 추가
          echo "import './apiKey.js';" | cat - ./script.js > ./script_temp.js
          mv ./script_temp.js ./script.js
