name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Debug environment
      run: |
        echo "Checking if MAPLE_API_KEY secret exists..."
        if [ -n "${{ env.MAPLE_API_KEY }}" ]; then
          echo "MAPLE_API_KEY secret is set"
        else
          echo "MAPLE_API_KEY secret is not set"
        fi

    - name: Create env.js
      run: |
        echo "Creating env.js file..."
        echo "window.env = { MAPLE_API_KEY: '${{ env.MAPLE_API_KEY }}' };" > env.js
        echo "env.js created successfully"
        ls -la env.js

    - name: Update HTML
      run: |
        echo "Updating PunchkingSuro.html..."
        sed -i '/<head>/a <script src="env.js"></script>' PunchkingSuro.html
        echo "HTML updated successfully"
        head -n 10 PunchkingSuro.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .


