name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAPLE_API_KEY: ${{ secrets.MAPLE_API_KEY }}

    steps:
    - uses: actions/checkout@v2

    - name: Replace API key
      run: |
        echo "Replacing API key..."
        sed -i 's/__MAPLE_API_KEY__/'"$MAPLE_API_KEY"'/g' PunchkingSuro.html
        echo "API key replacement completed"
        cat PunchkingSuro.html | grep MAPLE_API_KEY

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .



