name: Inject Secrets into .env

on:
  push:
    branches:
      - main

jobs:
  inject-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
           echo "MAPLE_API_KEY=${{ secrets.MAPLE_API_KEY }}" >> .env
