name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create env file with encoded API key
        run: |
          # 작업 디렉토리 내용 확인
          echo "Current directory contents:"
          ls -la
          
          # API 키를 Base64로 인코딩
          ENCODED_API_KEY=$(echo -n "${{ secrets.API }}" | base64)
          
          # JavaScript 파일 생성 (더 간단한 버전)
          cat > env.js << EOL
          window.env = {
            API: atob('${ENCODED_API_KEY}')
          };
          EOL
          
          echo "Created env.js contents:"
          cat env.js
          echo "Directory contents after env.js creation:"
          ls -la

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Create artifact directory
        run: |
          mkdir -p _site
          cp -r * _site/ || true
          echo "Contents of _site directory:"
          ls -la _site/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2


