name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Replace API key
      shell: bash
      run: |
        echo "Replacing API key..."
        echo "window.env = { MAPLE_API_KEY: '${{ secrets.MAPLE_API_KEY }}' };" > env.js
        echo '<script src="env.js"></script>' > temp.html
        cat PunchkingSuro.html >> temp.html
        mv temp.html PunchkingSuro.html
        echo "API key replacement completed"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .



