name: Deploy with Maple API Key

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Replace Maple API Key placeholder
      env:
        MAPLE_API_KEY: ${{ secrets.MAPLE_API_KEY }}
      run: |
        # Maple API 키를 script.js 파일에 삽입
        sed -i "s/const apiKey = .*$/const apiKey = '$MAPLE_API_KEY';/" script.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
