name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Replace API key
      shell: bash
      run: |
        echo "Creating env.js..."
        echo "window.env = { MAPLE_API_KEY: '${{ secrets.MAPLE_API_KEY }}' };" > env.js
        echo "Content of env.js:"
        cat env.js
        echo "Creating temp.html..."
        echo '<!DOCTYPE html><html><head><meta charset="UTF-8"><script src="env.js"></script>' > temp.html
        echo "Appending PunchkingSuro.html..."
        sed '1,/<html>/d' PunchkingSuro.html >> temp.html
        echo "Moving temp.html to PunchkingSuro.html..."
        mv temp.html PunchkingSuro.html
        echo "Final content of PunchkingSuro.html (first 10 lines):"
        head -n 10 PunchkingSuro.html
        echo "API key replacement completed"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .



